### ISSUE TITLE
Column names

### ISSUE THREAD

**Issue by kduskin** [hauselin/domain-quality-ratings#2]
Hi there, using this repo and referring back to the published manuscript there are two naming conventions I wanted to verify.
 
The first is that in the manuscript, the domains from Lasser et al. (2022) are referred to with the prefix "Lasser" e.g. "Lasser mean". In domain_ratings.csv there are no columns named that way, but there are "Lewandowsky" columns. Am I correct in inferring that those values are from the Lasser et al. (2022) paper? 

The second is the binary class column. In the manuscript it is referred to as "Iffy binary", but in domain_ratings.csv there is a column called "misinfome_bin" that fits the same criteria (binary labels, with 1388 non-zero entries). Is that column the iffy binary labels? 

Thanks!

**Comment by hauselin** [comment]
Yes, you're right in both cases!
